name: intro_to_bioinf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - bwa
  - samtools
  - bedtools
  - fastqc
  - tmux
  - snakemake
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - ipython
  # Additional useful packages for bioinformatics and Jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
