[workspace]
name = "python"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
marimo = "marimo edit"
python = "python"

[dependencies]
python = ">=3.11"
marimo = "*"
pandas = "*"
numpy = "*"
matplotlib = "*"
