[workspace]
channels = ["conda-forge", "bioconda"]
name = "biostatistics"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
r-base      = "*"
r-irkernel  = "*"
jupyterlab  = "*"
ipykernel   = "*"

python      = "*"

r-tidyverse    = "*"
r-ggplot2      = "*"
r-devtools     = "*"
r-scales       = "*"
r-viridis      = "*"
r-dplyr        = "*"
r-matrix       = "*"
r-plot3d       = "*"
r-terra        = "*"
r-raster       = "*"
r-jpeg         = "*"
r-interp       = "*"
r-maps         = "*"
r-latticeextra = "*"
r-mapdata      = "*"
r-biclust      = "*"
r-fnn          = "*"
r-igraph       = "*"
r-rarpack      = "*"
r-pak          = "*"
r-reticulate   = "*"
r-ppcor        = "*"


r-biocmanager = ">=1.30.27,<2"

[tasks]
jupyter = "jupyter lab --no-browser --ip=localhost --port=5555"
rstudio = "rstudio"
r_test = "R"
